version: "3.1"
services:
    whatsapp-chatgpt:
        build: ./
        container_name: whatsapp-chatgpt
        # read_only: true
        image: ghcr.io/dfmarulanda/whatsapp-chatgpt:geobristol
        environment:
            OPENAI_API_KEY: "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"
            OPENAI_GPT_MODEL: "gpt-4-1106-preview"
            PREFIX_ENABLED: "false"
            SERPAPI_API_KEY: ""
        restart: unless-stopped
        volumes:
            - session-data:/app/session
volumes:
    session-data:
